### ISSUE TITLE
Failed to Generate Config Files

### ISSUE THREAD

**Issue by blaise-muhirwa** [adinhodovic/django-mixin#11]
When I run `make prometheus_alerts.yaml`, I get this error (after cloning the repository and installing jsonnet-bundler of course)

```shell
Installing tools from hack/tools.go
build github.com/Azure/azure-sdk-for-go/sdk/azcore: cannot load github.com/Azure/azure-sdk-for-go/sdk/azcore: no Go source files
/bin/sh: 1: /home/ubuntu/ptdev/zuuul/monitoring/prometheus/django-mixin/tmp/bin/jsonnet: not found
make: *** [Makefile:30: prometheus_alerts.yaml] Error 127
```

**Comment by adinhodovic** [comment]
Hey blaise :)

The tools needed should be installed in the `django-mixin/tmp/bin` directory. This happens automatically when you run make prometheus_alerts.yaml. However, the pre-step of installing tools fails due to the `azure-sdk-for-go` package above.

Not sure why that is the case for you.

Output should be:

```sh
mkdir -p /home/adin/oss/django-mixin/tmp/bin
Installing tools from hack/tools.go
go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnet
go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnet-lint
go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnetfmt
go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/grafana/dashboard-linter
go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/prometheus/prometheus/cmd/promtool
```

**Comment by blaise-muhirwa** [comment]
> Hey blaise :)
> 
> The tools needed should be installed in the `django-mixin/tmp/bin` directory. This happens automatically when you run make prometheus_alerts.yaml. However, the pre-step of installing tools fails due to the `azure-sdk-for-go` package above.
> 
> Not sure why that is the case for you.
> 
> Output should be:
> 
> ```shell
> mkdir -p /home/adin/oss/django-mixin/tmp/bin
> Installing tools from hack/tools.go
> go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnet
> go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnet-lint
> go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnetfmt
> go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/grafana/dashboard-linter
> go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
> go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/prometheus/prometheus/cmd/promtool
> ```

I checked the `django-mixin/tmp/bin` subdirectory and I noticed that it's empty after running `make prometheus_alerts.yaml`.

**Comment by adinhodovic** [comment]
> > Hey blaise :)
> > The tools needed should be installed in the `django-mixin/tmp/bin` directory. This happens automatically when you run make prometheus_alerts.yaml. However, the pre-step of installing tools fails due to the `azure-sdk-for-go` package above.
> > Not sure why that is the case for you.
> > Output should be:
> > ```shell
> > mkdir -p /home/adin/oss/django-mixin/tmp/bin
> > Installing tools from hack/tools.go
> > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnet
> > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnet-lint
> > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnetfmt
> > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/grafana/dashboard-linter
> > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
> > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/prometheus/prometheus/cmd/promtool
> > ```
> 
> I checked the `django-mixin/tmp/bin` subdirectory and I noticed that it's empty after running `make prometheus_alerts.yaml`.

Try upgrading you system go version, and see if the go binaries get generated, unclear error you get.

**Comment by blaise-muhirwa** [comment]
> > > Hey blaise :)
> > > The tools needed should be installed in the `django-mixin/tmp/bin` directory. This happens automatically when you run make prometheus_alerts.yaml. However, the pre-step of installing tools fails due to the `azure-sdk-for-go` package above.
> > > Not sure why that is the case for you.
> > > Output should be:
> > > ```shell
> > > mkdir -p /home/adin/oss/django-mixin/tmp/bin
> > > Installing tools from hack/tools.go
> > > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnet
> > > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnet-lint
> > > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/google/go-jsonnet/cmd/jsonnetfmt
> > > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/grafana/dashboard-linter
> > > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
> > > go build '-mod=mod' -o /home/adin/oss/django-mixin/tmp/bin github.com/prometheus/prometheus/cmd/promtool
> > > ```
> > 
> > 
> > I checked the `django-mixin/tmp/bin` subdirectory and I noticed that it's empty after running `make prometheus_alerts.yaml`.
> 
> Try upgrading you system go version, and see if the go binaries get generated, unclear error you get.


Cool, thanks. I upgraded go and that seemed to work. However, I'm running into a different kind of error when I run the make command. 

```shell
# google.golang.org/grpc
/home/ubuntu/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:2082:14: undefined: atomic.Int64
note: module requires Go 1.19
go build '-mod=mod' -o /home/ubuntu/ptdev/zuuul/monitoring/prometheus/django-mixin/tmp/bin github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb 
go build '-mod=mod' -o /home/ubuntu/ptdev/zuuul/monitoring/prometheus/django-mixin/tmp/bin github.com/prometheus/prometheus/cmd/promtool 
# k8s.io/kube-openapi/pkg/cached
/home/ubuntu/go/pkg/mod/k8s.io/kube-openapi@v0.0.0-20230717233707-2695361300d9/pkg/cached/cache.go:285:16: undefined: atomic.Pointer
/home/ubuntu/go/pkg/mod/k8s.io/kube-openapi@v0.0.0-20230717233707-2695361300d9/pkg/cached/cache.go:286:16: undefined: atomic.Pointer
note: module requires Go 1.19
# k8s.io/client-go/tools/cache/synctrack
/home/ubuntu/go/pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/synctrack/lazy.go:29:15: undefined: atomic.Pointer
note: module requires Go 1.20
# go.opentelemetry.io/otel/internal/global
/home/ubuntu/go/pkg/mod/go.opentelemetry.io/otel@v1.19.0/internal/global/handler.go:44:18: undefined: atomic.Pointer
/home/ubuntu/go/pkg/mod/go.opentelemetry.io/otel@v1.19.0/internal/global/internal_logging.go:30:25: undefined: atomic.Pointer
note: module requires Go 1.20
# github.com/klauspost/compress/zstd
/home/ubuntu/go/pkg/mod/github.com/klauspost/compress@v1.17.2/zstd/dict.go:479:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
/home/ubuntu/go/pkg/mod/github.com/klauspost/compress@v1.17.2/zstd/dict.go:490:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
/home/ubuntu/go/pkg/mod/github.com/klauspost/compress@v1.17.2/zstd/dict.go:491:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
/home/ubuntu/go/pkg/mod/github.com/klauspost/compress@v1.17.2/zstd/dict.go:492:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
# google.golang.org/grpc
/home/ubuntu/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:2082:14: undefined: atomic.Int64
note: module requires Go 1.19
# go.uber.org/multierr
/home/ubuntu/go/pkg/mod/go.uber.org/multierr@v1.11.0/error.go:209:20: undefined: atomic.Bool
note: module requires Go 1.19
make: *** [Makefile:72: /home/ubuntu/ptdev/zuuul/monitoring/prometheus/django-mixin/tmp/bin/jsonnet] Error 123
```

**Comment by blaise-muhirwa** [comment]
Ah never mind! I saw that it's also a Go version issue.
