### ISSUE TITLE
Missing namespace

### ISSUE THREAD

**Issue by timborden** [adinhodovic/django-mixin#12]
Thanks for sharing these dashboards!

Our `django-prometheus` is set up with the same configuration as your [blog post](https://hodovi.cc/blog/django-monitoring-with-prometheus-and-grafana/) ...but we don't have a `namespace` label in the metrics and the `job` label is always "django"...so the dashboards aren't working. 

There is a `PROMETHEUS_METRIC_NAMESPACE` env var for `django-prometheus` that we could use, but that adds a prefix to all [metrics](https://github.com/korfuri/django-prometheus?tab=readme-ov-file#configuration) instead of a label.

What am I missing?

**Comment by timborden** [comment]
Nevermind...I figured out the issue. I'd set the scrape interval in Mimir at `60s` which didn't work with the rate interval in the dashboard. Updating the scrape interval to `15s` fixed the issue.

**Comment by adinhodovic** [comment]
Interesting, I thought you might be running in a non-k8s environment therefore the namespace is missing.
